### ISSUE TITLE
please add 6s1 answer key (also update the other ones)

### ISSUE THREAD

**Issue by anuraglol** [skndash96/jee-scorecard#1]

**Comment by 0xMukesh** [comment]
@skndash96 here's 5s2 answer key - https://json.extendsclass.com/bin/14c566465f21 and 6s1 answer key - https://json.extendsclass.com/bin/61c3a6fdc56d

**Comment by armoredvortex** [comment]
[04s2.json](https://github.com/skndash96/jee-scorecard/files/14962916/04s2.json)
Attatched 4s2

**Comment by skndash96** [comment]
All shifts are added.
